# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build @eshop/eshop`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t eshop-eshop`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system eshop-eshop && \
          adduser --system -G eshop-eshop eshop-eshop

COPY apps/eshop/dist eshop-eshop/
COPY apps/eshop/package.json eshop-eshop/
RUN chown -R eshop-eshop:eshop-eshop .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix eshop-eshop --omit=dev -f install

CMD [ "node", "eshop-eshop" ]
